apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
    project: istio-course
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicemesh-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend
    version: v1
    project: istio-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
      project: istio-course
  template:
    metadata:
      labels:
        app: frontend
        version: v1
        project: istio-course
    spec:
      serviceAccountName: servicemesh-frontend
      containers:
        - name: frontend
          image: illia-korotia:v1
          imagePullPolicy: IfNotPresent #Or use Always to download it from dockerhub
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500M"
              cpu: "0.10"
            limits:
              memory: "1500M"
              cpu: "0.10"